In [61]:
from statistics import LinearRegression

import pandas as pd
import numpy as np
from sklearn.linear_model import ElasticNet,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.metrics import classification_report, mean_absolute_error, r2_score, f1_score, accuracy_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis,QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier, VotingRegressor, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor


In [55]:
sonar=pd.read_csv("Sonar.csv")
y=sonar["Class"]
X=sonar.drop("Class",axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)



In [56]:
dtc=DecisionTreeClassifier()
knn=KNeighborsClassifier()
nb=GaussianNB()
knn2=KNeighborsClassifier()
Voting=VotingClassifier(estimators=[("Tree",dtc),("KNN",knn),("KNN2",knn2),("NB",nb)],voting="soft",weights=[7.6,7.5,8.1,6.3])
Voting.fit(X_train,y_train)
y_pred=Voting.predict(X_test)
print(classification_report(y_test,y_pred))
print(y_pred)
y_pred0=Voting.estimators_[0].predict(X_test)
print(y_pred0)
y_pred1=Voting.estimators_[1].predict(X_test)
print(y_pred1)
y_pred2=Voting.estimators_[2].predict(X_test)
y_pred_series   = pd.Series(y_pred, name="y_pred_Voting") # Use a distinct name for the Voting result
y_pred0_series  = pd.Series(y_pred0, name="Tree")
y_pred1_series  = pd.Series(y_pred1, name="Knn")
y_pred2_series  = pd.Series(y_pred2, name="NB")

predictions_dict = {
    "Tree": y_pred0_series,
    "Knn": y_pred1_series,
    "NB": y_pred2_series,
    "y_pred_Voting": y_pred_series
}

df = pd.DataFrame(predictions_dict)

print(df.head(5))
for i in range(len(Voting.estimators_)):
    print(i)
    print(accuracy_score(y_test,Voting.estimators_[i].predict(X_test)))

              precision    recall  f1-score   support

           0       0.74      0.94      0.83        34
           1       0.90      0.62      0.73        29

    accuracy                           0.79        63
   macro avg       0.82      0.78      0.78        63
weighted avg       0.82      0.79      0.79        63

[1 0 1 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1]
[1 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1 1 0 0
 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 1 0 0 1]
[1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1]
   Tree  Knn  NB  y_pred_Voting
0     1    1   1              1
1     0    0   0              0
2     0    1   1              1
3     1    1   1              1
4     0    1   1              1
0
0.746031746031746
1
0.746031746031746
2
0.746031746031746
3
0.6349206349206349


In [57]:
from sklearn.metrics import log_loss

Voting=VotingClassifier(estimators=[("Tree",dtc),("KNN",knn),("KNN2",knn2),("NB",nb)],voting="soft",weights=[7.6,7.5,8.1,6.3])
Voting.fit(X_train,y_train)
y_pred=Voting.predict(X_test)
print(classification_report(y_test,y_pred))
y_pred_prob=Voting.predict_proba(X_test)
print(log_loss(y_test,y_pred_prob))

              precision    recall  f1-score   support

           0       0.71      0.94      0.81        34
           1       0.89      0.55      0.68        29

    accuracy                           0.76        63
   macro avg       0.80      0.75      0.75        63
weighted avg       0.79      0.76      0.75        63

0.44382727021927054


In [58]:
hr=pd.read_csv('HR_comma_sep.csv',index_col=0)
X=hr.drop(["left"],axis=1)
y=hr['left']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)
ohe=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
X_train_trf=ohe.fit_transform(X_train)
X_test_trf=ohe.transform(X_test)
dtc=DecisionTreeClassifier()
knn=KNeighborsClassifier()
nb=GaussianNB()
knn2=KNeighborsClassifier()
Voting=VotingClassifier(estimators=[("Tree",dtc),("KNN",knn),("KNN2",knn2),("NB",nb)],weights=[7.6,7.5,8.1,6.3])
Voting.fit(X_train_trf,y_train)
y_pred=Voting.predict(X_test_trf)
print(classification_report(y_test,y_pred))
print(y_pred)
y_pred0=Voting.estimators_[0].predict(X_test_trf)
print(y_pred0)
y_pred1=Voting.estimators_[1].predict(X_test_trf)
print(y_pred1)
y_pred2=Voting.estimators_[2].predict(X_test_trf)
y_pred_series   = pd.Series(y_pred, name="y_pred_Voting") # Use a distinct name for the Voting result
y_pred0_series  = pd.Series(y_pred0, name="Tree")
y_pred1_series  = pd.Series(y_pred1, name="Knn")
y_pred2_series  = pd.Series(y_pred2, name="NB")

predictions_dict = {
    "Tree": y_pred0_series,
    "Knn": y_pred1_series,
    "NB": y_pred2_series,
    "y_pred_Voting": y_pred_series
}

df = pd.DataFrame(predictions_dict)

print(df.head(5))
for i in range(len(Voting.estimators_)):
    print(i)
    print(accuracy_score(y_test,Voting.estimators_[i].predict(X_test_trf)))
from sklearn.metrics import log_loss

Voting=VotingClassifier(estimators=[("Tree",dtc),("KNN",knn),("KNN2",knn2),("NB",nb)],voting="soft",weights=[9.7,9.6,9.5,7.1])
Voting.fit(X_train_trf,y_train)
y_pred=Voting.predict(X_test_trf)
print(classification_report(y_test,y_pred))
y_pred_prob=Voting.predict_proba(X_test_trf)
print(log_loss(y_test,y_pred_prob))

              precision    recall  f1-score   support

           0       0.96      0.91      0.94      3429
           1       0.76      0.87      0.81      1070

    accuracy                           0.91      4499
   macro avg       0.86      0.89      0.88      4499
weighted avg       0.91      0.91      0.91      4499

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 1]
[0 0 0 ... 1 0 0]
   Tree  Knn  NB  y_pred_Voting
0     0    0   0              0
1     0    0   0              0
2     0    0   0              0
3     0    1   1              1
4     0    0   0              0
0
0.9517670593465215
1
0.9053122916203601
2
0.9053122916203601
3
0.6210268948655256
              precision    recall  f1-score   support

           0       0.98      0.93      0.96      3429
           1       0.81      0.95      0.87      1070

    accuracy                           0.93      4499
   macro avg       0.90      0.94      0.91      4499
weighted avg       0.94      0.93      0.94      4499

0.31345517571571

In [59]:
concrete=pd.read_csv("Concrete_Data.csv")
y=concrete["Strength"]
X=concrete.drop(["Strength"],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=25)


In [66]:
dtr1=DecisionTreeRegressor(random_state=25)
dtr2=DecisionTreeRegressor(random_state=25,max_depth=5)
lr=LinearRegression()
el=ElasticNet()
voting=VotingRegressor([("DTR1",dtr1),("DTR2",dtr2),("Lr",lr),('EL',el)],weights=[10,5,1,4])
voting.fit(X_train,y_train)
y_pred=voting.predict(X_test)
print(r2_score(y_test,y_pred))
for i in range(len(voting.estimators_)):
    print(r2_score(y_test,voting.estimators_[i].predict(X_test)))

0.8551747917916809
0.8127760533837747
0.7311101169515943
0.6351839142464111
0.6345321364921961


In [ ]:
sonar=pd.read_csv("Sonar.csv")
y=sonar["Class"]
X=sonar.drop("Class",axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25,stratify=y)
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)